### PR TITLE
Fixing multi-byte characters parsing from the server

### LINKED ISSUE #315: Properly handle large requests using multi byte chars

### PR DESCRIPTION
**Pull request by ayende**
Fixed #315 and RDBC-593

### CODE REVIEW

File: src/Http/RavenCommandResponsePipeline.ts [hunk 1]
```diff
@@ -172,19 +172,27 @@ export class RavenCommandResponsePipeline<TStreamResult> extends EventEmitter {
...
+            const bytesChunks = [];
             const parseJsonSyncTransform = new stream.Transform({
                 readableObjectMode: true,
                 transform(chunk, enc, callback) {
-                    jsonChunks.push(chunk.toString("utf8"));
+                    bytesChunks.push(chunk);
                     callback();
                 },
                 flush(callback) {
+                    var str = null;
```
Comment (gregolsky) [inline src/Http/RavenCommandResponsePipeline.ts]:
```suggestion
                    let str = null;

```

File: test/Issues/Github_315.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    beforeEach(async function () {
+        store = await testContext.getDocumentStore();
+    });
+
+    afterEach(async () =>
+        await disposeTestDocumentStore(store));
+
+    it("can use complex multi byte characters on load", async () => {
+
+        var str = '🐛'.repeat(50_000);
```
Comment (gregolsky) [inline test/Issues/Github_315.ts]:
```suggestion
        let str = '🐛'.repeat(50_000);
```

File: test/Ported/Issues/RavenDB_15497.ts [hunk 3]
```diff
@@ -54,9 +54,9 @@ describe("RavenDB_15497", function () {
 
             await assertThrows(() => session.saveChanges(), e => {
                 assertThat(e.name)
-                    .isEqualTo("TimeoutException");
```
Comment (gregolsky) [inline test/Ported/Issues/RavenDB_15497.ts:57]: That isn't that easy. There's some logic based on that somewhere. I think it's better leave it for Marcin to handle and leave a failing test.

File: test/Issues/Github_315.ts [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+        {
+            var session = store.openSession();
+            var doc = {'str': str};
+            await session.store(doc, "items/1");
+            await session.saveChanges();
+        }
+
+        {
+            var session = store.openSession();
+            var item = await session.load("items/1");
```
Comment (gregolsky) [inline test/Issues/Github_315.ts]:
```suggestion
            let item = await session.load("items/1");
```
